source 'https://github.com/CocoaPods/Specs'

platform :ios, '9.0'
use_frameworks!

#-------------- CocoaPods 1.X ---------------

inhibit_all_warnings!
project 'github.xcodeproj'

def sharedPods
  pod 'RxSwift', '~> 2.0'
  pod 'RxCocoa', '~> 2.0'
  pod 'Moya/RxSwift'
  pod 'SwiftyJSON'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
#, :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

def testPods
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'RxBlocking', '~> 2.0'
end

target 'github' do
  sharedPods
end

target 'githubTests' do
  sharedPods
  testPods
end
